'use strict';

let emojis = [
    { icon: '😀', id: 1 },
    { icon: '😃', id: 2 },
    { icon: '😄', id: 3 },
    { icon: '😆', id: 4 },
    { icon: '😇', id: 5 },
    { icon: '😉', id: 6 },
    { icon: '😊', id: 7 },
    { icon: '😋', id: 8 },
    { icon: '😍', id: 9 },
    { icon: '😜', id: 10 },
    { icon: '😝', id: 11 },
    { icon: '😛', id: 12 },
    { icon: '😎', id: 13 },
    { icon: '😏', id: 14 },
    { icon: '😑', id: 15 },
    { icon: '😒', id: 16 },
    { icon: '😳', id: 17 },
    { icon: '😠', id: 18 },
    { icon: '👹', id: 19 },
    { icon: '😈', id: 20 },
    { icon: '💀', id: 21 },
    { icon: '👻', id: 22 },
    { icon: '🎅', id: 23 },
    { icon: '😺', id: 24 },
    { icon: '👱', id: 25 },
    { icon: '👩', id: 26 },
    { icon: '👦', id: 27 },
    { icon: '👧', id: 28 },
    { icon: '👴', id: 29 },
    { icon: '👵', id: 30 },
    { icon: '👮', id: 31 },
    { icon: '🕵', id: 32 },
    { icon: '👰', id: 33 },
    { icon: '💃', id: 34 },
    { icon: '💂', id: 35 },
    { icon: '👽', id: 36 },
    { icon: '🔒', id: 37 },
    { icon: '🔑', id: 38 },
    { icon: '🤨', id: 38 },
    { icon: '🤔', id: 39 },
    { icon: '😫', id: 40 },
    { icon: '😓', id: 41 },
    { icon: '😔', id: 42 },
    { icon: '🤑', id: 43 },
    { icon: '😲', id: 44 },
    { icon: '😞', id: 45 },
    { icon: '😢', id: 46 },
    { icon: '😭', id: 47 },
    { icon: '🤯', id: 48 },
    { icon: '😱', id: 49 },
    { icon: '🤪', id: 50 },
];

module.exports = emojis;

