POST {{host}}/api/protected/plan
Content-Type: application/json
Authorization: {{token}}
Supper: {{supper_token}}

{
  "creator": "{{user_id}}",
  "name": "Teste novo plano com tipo sem tipo",
  "interval": 1,
  "intervalType": "months",
  "valueCents": 101,
  "payableWith": "credit_card",
  "textLabels": [
     { "value": "6", "description": "Consultas Completas" },
     {  "value": "10%",  "description": "de desconto nas consultas" }
  ],
  "description": "Teste novo plano"
}

###